### PR TITLE
I did the categ,product

### PR DESCRIPTION
**Pull request by BEDIAKO20**

### CODE REVIEW

**Comment by samgenerals10** [comment]
worked on the homepage

**Comment by samgenerals10** [comment]
good

**Review by samgenerals10 — COMMENTED** [review]
good

**Comment by BEDIAKO20** [comment]
ggg

**Comment by BEDIAKO20** [comment]
https://meet.google.com/sxd-ncqi-ehi

**Comment by samgenerals10** [comment]
i thought the meeting link

**Comment by samgenerals10** [comment]
https://meet.google.com/sxd-ncqi-ehi

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by samgenerals10** [comment]
*Yesterday, I gave us a list of the participating companies, let's look at
them again but this time, with their websites 👇🏽👇🏽👇🏽*


*Participating Companies and Their Job Boards:*

Here are the 8 companies:

1️⃣ Ada: https://boards.greenhouse.io/ada18


2️⃣ AlayaCare: https://alayacare.com/open-positions/


3️⃣ CellCarta: https://cellcarta.com/careers/


4️⃣ Clarius: https://clarius.com/ca/about/careers/


5️⃣ Clio: https://www.clio.com/about/careers/


6️⃣ DPG: https://duchesnaypharmaceuticalgroup.com/en/careers


7️⃣ Lightspeed: https://www.lightspeedhq.com/careers/


8️⃣ Vive: https://www.vivecrop.com/career



These companies are part of the GHP and are actively seeking skilled
workers in NOC categories 0, 1, 2, and 3.



*By applying to these companies, you can leverage the fast-track work
permit processing and avoid the LMIA requirement.*



*What You Should Do Next:*



1️⃣ Visit the job boards linked above.



2️⃣ Look for job openings that match your skills and experience.



3️⃣ Apply directly through the company's website.



*This is a great opportunity to start your journey to Canada quickly and
efficiently.*

 *If you need any help with your applications or have questions about the
process, feel free to reach out to me.*


*Tomorrow we'll end the training session, by giving you critical tips and
strategies you can use to increase your chances of getting the job, so
don't miss it*

Remember to give a thumbs up if you found this valuable ✅

I wish you success in your applications! 😊


Mr David
Global Intels Hub

**Pull request merged**
